name: Check for New Pipedrive Interactions and Add to Orbit
on:
  schedule:
    - cron: "0 0 */1 * *"
  workflow_dispatch:
jobs:
  comments-workflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Set up Ruby 2.7.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
    - name: Bundle Install
      run: |
        gem update --system 3.1.4 -N
        gem install --no-document pipedrive_orbit
    - name: Check for New Deal Notes
      run: |
        pipedrive_orbit --check-notes
      env:
        LINKEDIN_ORGANIZATION: ${{ secrets.PIPEDRIVE_URL }}
        LINKEDIN_TOKEN: ${{ secrets.PIPEDRIVE_API_KEY }}
        ORBIT_API_KEY: ${{ secrets.ORBIT_API_KEY }}
        ORBIT_WORKSPACE_ID: ${{ secrets.ORBIT_WORKSPACE_ID }}
    - name: Check for New People Notes
      run: |
        pipedrive_orbit --check-people-notes
      env:
        LINKEDIN_ORGANIZATION: ${{ secrets.PIPEDRIVE_URL }}
        LINKEDIN_TOKEN: ${{ secrets.PIPEDRIVE_API_KEY }}
        ORBIT_API_KEY: ${{ secrets.ORBIT_API_KEY }}
        ORBIT_WORKSPACE_ID: ${{ secrets.ORBIT_WORKSPACE_ID }}
    - name: Check for New Deal Activities
      run: |
        pipedrive_orbit --check-activities
      env:
        LINKEDIN_ORGANIZATION: ${{ secrets.PIPEDRIVE_URL }}
        LINKEDIN_TOKEN: ${{ secrets.PIPEDRIVE_API_KEY }}
        ORBIT_API_KEY: ${{ secrets.ORBIT_API_KEY }}
        ORBIT_WORKSPACE_ID: ${{ secrets.ORBIT_WORKSPACE_ID }}